package org.firstinspires.ftc.teamcode.Robot.Controls;

import com.qualcomm.robotcore.hardware.Gamepad;

import org.firstinspires.ftc.robotcore.external.Telemetry;
import org.firstinspires.ftc.teamcode.Helpers.ButtonHelper;
import org.firstinspires.ftc.teamcode.Robot.GoalAimController;
import org.firstinspires.ftc.teamcode.Robot.Subsystems.Gate;
import org.firstinspires.ftc.teamcode.Robot.Subsystems.Intake;
import org.firstinspires.ftc.teamcode.Robot.Subsystems.Shooter;

import static org.firstinspires.ftc.teamcode.Robot.HamiltonParams.*;

public class OperatorControls {

    private final Intake intake;
    private final Gate gate;
    private final Shooter shooter;
    private final Telemetry telemetry;
    private final GoalAimController aimController;

    private String userFeedback = "";
    private long feedbackTimer = 0;

    private static final int FEEDBACK_DISPLAY_MS = 2000;

    /*
     * Start at an impossible state so constructor
     * setState(STATE_INTAKING) actually runs the
     * intake and transfer commands.
     */
    private byte intakeTransferState = -1;

    private static final byte STATE_INTAKING = 0;
    private static final byte STATE_HOLDING = 1;
    private static final byte STATE_SHOOTING = 2;

    private static final String[] STATE_FEEDBACK_STRINGS = {
            "State: INTAKING",
            "State: HOLDING",
            "State: SHOOTING"
    };

    private static final double INTAKING_INTAKE_POWER = 1.0;
    private static final double INTAKING_TRANSFER_POWER = 0.30;

    private static final double HOLDING_INTAKE_POWER = 0.0;
    private static final double HOLDING_TRANSFER_POWER = 0.0;

    private static final double SHOOTING_INTAKE_POWER = 0.9;
    private static final long SHOOTING_DURATION_MS = 650;

    private static final double SHOOTER_IDLE_VELOCITY = 1600.0;

    private long actualShootingStartedAtMs = 0;

    private boolean waitingToStartShooting = false;
    private boolean autoAlignEnabled = false;
    private boolean requestAutoAlignDisable = false;

    // Distance from robot to the configured shooter target.
    private double distanceToTarget = 0.0;

    // Stationary target generated by the shot table.
    private double baseLookupVelocity = 1700.0;

    // Final target after moving-shot compensation.
    private double lookupTargetVelocity = 1700.0;

    // Filtered field-centric robot velocity.
    private double filteredRobotVelX = 0.0;
    private double filteredRobotVelY = 0.0;

    // Robot velocity projected onto the line to the goal.
    private double velocityTowardsGoal = 0.0;

    // Shooter correction produced by robot movement.
    private double kinematicCorrection = 0.0;

    private static final double[][] SHOT_TABLE = {
            {40.0, 1573.67},
            {45.0, 1568.66},
            {50.0, 1566.29},
            {55.0, 1566.55},
            {60.0, 1569.45},
            {65.0, 1574.98},
            {70.0, 1583.14},
            {75.0, 1582.87},
            {80.0, 1587.90},
            {85.0, 1613.02},
            {90.0, 1628.10},
            {95.0, 1663.44},
            {100.0, 1687.39},
            {105.0, 1713.99},
            {110.0, 1743.21},
            {115.0, 1775.07},
            {120.0, 1809.56},
            {125.0, 1846.69},
            {130.0, 1886.45},
            {135.0, 1928.84},
            {140.0, 1973.86},
            {145.0, 2021.52},
            {150.0, 2090.40},
            {155.0, 2200.95},
            {160.0, 2331.60}
    };

    private double commandedShooterVelocity = 0.0;
    private double lastSentShooterVelocity = -999.0;

    private final ButtonHelper btnRightBumper =
            new ButtonHelper();

    public OperatorControls(
            Intake intake,
            Shooter shooter,
            Telemetry telemetry,
            Gate gate,
            GoalAimController aimController
    ) {
        this.intake = intake;
        this.shooter = shooter;
        this.telemetry = telemetry;
        this.gate = gate;
        this.aimController = aimController;

        setState(
                STATE_INTAKING,
                false,
                0
        );

        gate.block();
    }

    public void setAutoAlignEnabled(boolean enabled) {
        if (autoAlignEnabled == enabled) {
            return;
        }

        autoAlignEnabled = enabled;

        waitingToStartShooting = false;
        actualShootingStartedAtMs = 0;

        /*
         * Force the next loop to send the new mode's exact
         * shooter target, even if the previous and new
         * velocities are very close.
         */
        lastSentShooterVelocity = -999.0;

        if (enabled) {
            gate.open();

            setState(
                    STATE_HOLDING,
                    false,
                    0
            );
        } else {
            gate.block();

            setState(
                    STATE_INTAKING,
                    false,
                    0
            );
        }
    }

    public boolean shouldDisableAutoAlign() {
        return requestAutoAlignDisable;
    }

    public void clearDisableAutoAlignRequest() {
        requestAutoAlignDisable = false;
    }

    public boolean isIntaking() {
        return intakeTransferState == STATE_INTAKING;
    }

    public boolean isShooting() {
        return intakeTransferState == STATE_SHOOTING;
    }

    public void update(
            Gamepad g2,
            double poseX,
            double poseY,
            double velX,
            double velY,
            long nowMs,
            long nowNs,
            double loopDtSec
    ) {
        /*
         * Update the stationary distance lookup and
         * moving-shot correction every loop.
         */
        updateShooterTargets(
                poseX,
                poseY,
                velX,
                velY,
                loopDtSec
        );

        /*
         * Send the newest target before checking
         * whether the shooter is ready.
         */
        updateShooterCommand();

        updateIntakeStateMachine(
                g2,
                nowMs
        );

        /*
         * A shooting request does not immediately feed.
         * Wait until both flywheels are close to the
         * currently adjusted target.
         */
        if (intakeTransferState == STATE_SHOOTING
                && waitingToStartShooting) {

            if (shooter.isReadyToShoot()) {
                intake.intakeBoth(
                        SHOOTING_INTAKE_POWER
                );

                waitingToStartShooting = false;
                actualShootingStartedAtMs = nowMs;

                userFeedback = "ACTION: SHOOTING";
                feedbackTimer = nowMs;
            } else {
                /*
                 * Continue holding the ball while
                 * the flywheels reach the target.
                 */
                intake.intake(
                        HOLDING_INTAKE_POWER
                );

                intake.transferOut(
                        HOLDING_TRANSFER_POWER
                );
            }
        }
    }

    private void updateIntakeStateMachine(
            Gamepad g2,
            long nowMs
    ) {
        if (btnRightBumper.wasPressed(g2.right_bumper)
                && autoAlignEnabled) {

            /*
             * This requests a shot but does not
             * immediately feed the ball.
             */
            setState(
                    STATE_SHOOTING,
                    true,
                    nowMs
            );

            userFeedback = "ACTION: SHOOT REQUESTED";
            feedbackTimer = nowMs;

            return;
        }

        if (intakeTransferState == STATE_SHOOTING) {
            /*
             * Stay in the shooting state while waiting
             * for the shooter to reach velocity.
             */
            if (waitingToStartShooting) {
                return;
            }

            /*
             * After feeding starts, continue for the
             * configured fixed duration.
             */
            if (nowMs - actualShootingStartedAtMs
                    < SHOOTING_DURATION_MS) {

                return;
            }

            requestAutoAlignDisable = true;

            setState(
                    STATE_INTAKING,
                    true,
                    nowMs
            );

            return;
        }

        final byte desired =
                autoAlignEnabled
                        ? STATE_HOLDING
                        : STATE_INTAKING;

        if (intakeTransferState != desired) {
            setState(
                    desired,
                    true,
                    nowMs
            );
        }
    }

    private void setState(
            byte newState,
            boolean showFeedback,
            long nowMs
    ) {
        if (intakeTransferState == newState) {
            return;
        }

        intakeTransferState = newState;

        switch (newState) {
            case STATE_INTAKING:
                waitingToStartShooting = false;

                intake.intake(
                        INTAKING_INTAKE_POWER
                );

                intake.transferIn(
                        INTAKING_TRANSFER_POWER
                );

                break;

            case STATE_HOLDING:
                waitingToStartShooting = false;

                intake.intake(
                        HOLDING_INTAKE_POWER
                );

                intake.transferOut(
                        HOLDING_TRANSFER_POWER
                );

                break;

            case STATE_SHOOTING:
                /*
                 * Stop the feed motors first.
                 * update() starts them only after
                 * shooter.isReadyToShoot() becomes true.
                 */
                intake.stopAll();
                waitingToStartShooting = true;

                break;

            default:
                /*
                 * Protect against an invalid state.
                 */
                intake.stopAll();
                waitingToStartShooting = false;

                break;
        }

        if (showFeedback
                && newState >= 0
                && newState < STATE_FEEDBACK_STRINGS.length) {

            userFeedback =
                    STATE_FEEDBACK_STRINGS[newState];

            feedbackTimer = nowMs;
        }
    }

    private void updateShooterCommand() {
        final double targetVelocity =
                autoAlignEnabled
                        ? lookupTargetVelocity
                        : SHOOTER_IDLE_VELOCITY;

        commandedShooterVelocity =
                targetVelocity;

        if (shouldUpdateShooterVelocity(
                targetVelocity,
                lastSentShooterVelocity
        )) {
            shooter.setVelocity(
                    targetVelocity
            );

            lastSentShooterVelocity =
                    targetVelocity;
        }
    }

    private boolean shouldUpdateShooterVelocity(
            double newVel,
            double lastVel
    ) {
        final double diff =
                newVel - lastVel;

        return diff > SHOOTER_COMMAND_EPSILON
                || diff < -SHOOTER_COMMAND_EPSILON;
    }

    /**
     * Calculates:
     *
     * 1. Distance-based stationary shooter target.
     * 2. Filtered field-centric robot velocity.
     * 3. Robot velocity projected toward the goal.
     * 4. Final compensated shooter target.
     *
     * Positive velocityTowardsGoal means the robot is
     * moving toward the goal, so shooter velocity is reduced.
     *
     * Negative velocityTowardsGoal means the robot is
     * moving away from the goal, so shooter velocity is increased.
     */
    private void updateShooterTargets(
            double poseX,
            double poseY,
            double velX,
            double velY,
            double dtSec
    ) {
        final double targetX =
                aimController.getShooterTargetX();

        final double targetY =
                aimController.getShooterTargetY();

        final double dx =
                targetX - poseX;

        final double dy =
                targetY - poseY;

        distanceToTarget =
                Math.hypot(dx, dy);

        baseLookupVelocity =
                velocityFromShotTable(
                        distanceToTarget
                );

        /*
         * Reject invalid localization velocity values.
         */
        if (!Double.isFinite(velX)) {
            velX = 0.0;
        }

        if (!Double.isFinite(velY)) {
            velY = 0.0;
        }

        /*
         * Clamp loop delta time so a timing anomaly cannot
         * produce an invalid filter coefficient.
         */
        final double safeDtSec =
                clamp(
                        dtSec,
                        0.0001,
                        0.1
                );

        final double filterTauSec =
                Math.max(
                        0.0,
                        SHOOTER_ROBOT_VEL_FILTER_TAU_SEC
                );

        final double filterAlpha;

        if (filterTauSec < 1.0e-6) {
            /*
             * A zero filter time constant disables filtering.
             */
            filterAlpha = 1.0;
        } else {
            filterAlpha =
                    safeDtSec
                            / (filterTauSec + safeDtSec);
        }

        filteredRobotVelX +=
                filterAlpha
                        * (velX - filteredRobotVelX);

        filteredRobotVelY +=
                filterAlpha
                        * (velY - filteredRobotVelY);

        velocityTowardsGoal = 0.0;
        kinematicCorrection = 0.0;

        /*
         * Avoid dividing by zero if the robot is
         * exactly at the target coordinate.
         */
        if (distanceToTarget > 0.001) {
            final double directionToGoalX =
                    dx / distanceToTarget;

            final double directionToGoalY =
                    dy / distanceToTarget;

            /*
             * Dot product between robot velocity and
             * the unit vector toward the goal.
             */
            velocityTowardsGoal =
                    filteredRobotVelX
                            * directionToGoalX
                            + filteredRobotVelY
                            * directionToGoalY;

            /*
             * Convert inches/second of radial robot
             * velocity into encoder ticks/second of
             * shooter correction.
             */
            kinematicCorrection =
                    velocityTowardsGoal
                            * SHOOTER_KINEMATIC_COMP;

            /*
             * Prevent a temporary velocity spike from
             * causing a large shooter command.
             */
            final double maxCorrection =
                    Math.abs(
                            SHOOTER_KINEMATIC_MAX_CORRECTION
                    );

            kinematicCorrection =
                    clamp(
                            kinematicCorrection,
                            -maxCorrection,
                            maxCorrection
                    );
        }

        /*
         * Moving toward the goal:
         * positive correction, so shooter target decreases.
         *
         * Moving away from the goal:
         * negative correction, so shooter target increases.
         */
        lookupTargetVelocity =
                Math.max(
                        0.0,
                        baseLookupVelocity
                                - kinematicCorrection
                );
    }

    private double velocityFromShotTable(
            double distance
    ) {
        if (distance <= SHOT_TABLE[0][0]) {
            return SHOT_TABLE[0][1];
        }

        for (int i = 0;
             i < SHOT_TABLE.length - 1;
             i++) {

            final double d0 =
                    SHOT_TABLE[i][0];

            final double v0 =
                    SHOT_TABLE[i][1];

            final double d1 =
                    SHOT_TABLE[i + 1][0];

            final double v1 =
                    SHOT_TABLE[i + 1][1];

            if (distance <= d1) {
                final double t =
                        (distance - d0)
                                / (d1 - d0);

                return v0
                        + t * (v1 - v0);
            }
        }

        return SHOT_TABLE[
                SHOT_TABLE.length - 1
                ][1];
    }

    public void stopAll() {
        intake.stopAll();
        shooter.stop();
        gate.block();

        waitingToStartShooting = false;
        actualShootingStartedAtMs = 0;

        commandedShooterVelocity = 0.0;
        lastSentShooterVelocity = -999.0;

        filteredRobotVelX = 0.0;
        filteredRobotVelY = 0.0;

        velocityTowardsGoal = 0.0;
        kinematicCorrection = 0.0;
    }

    public void updateTelemetry(long nowMs) {
        if (telemetry == null) {
            return;
        }

        if (nowMs - feedbackTimer
                < FEEDBACK_DISPLAY_MS) {

            telemetry.addData(
                    "Operator",
                    userFeedback
            );
        }

        final String stateFeedback;

        if (intakeTransferState >= 0
                && intakeTransferState
                < STATE_FEEDBACK_STRINGS.length) {

            stateFeedback =
                    STATE_FEEDBACK_STRINGS[
                            intakeTransferState
                            ];
        } else {
            stateFeedback =
                    "State: UNKNOWN";
        }

        telemetry.addData(
                "Transfer State",
                stateFeedback
        );

        telemetry.addData(
                "Shooter Mode",
                autoAlignEnabled
                        ? "DISTANCE + MOTION"
                        : "IDLE"
        );

        telemetry.addData(
                "Idle Velocity",
                SHOOTER_IDLE_VELOCITY
        );

        telemetry.addData(
                "Shooter Ready",
                shooter.isReadyToShoot()
        );

        telemetry.addData(
                "Target Distance",
                distanceToTarget
        );

        telemetry.addData(
                "Base Lookup Vel",
                baseLookupVelocity
        );

        telemetry.addData(
                "Filtered Robot Vel X",
                filteredRobotVelX
        );

        telemetry.addData(
                "Filtered Robot Vel Y",
                filteredRobotVelY
        );

        telemetry.addData(
                "Velocity Toward Goal",
                velocityTowardsGoal
        );

        telemetry.addData(
                "Kinematic Mult",
                SHOOTER_KINEMATIC_COMP
        );

        telemetry.addData(
                "Kinematic Correction",
                kinematicCorrection
        );

        telemetry.addData(
                "Adjusted Lookup Vel",
                lookupTargetVelocity
        );

        telemetry.addData(
                "Commanded Shooter",
                commandedShooterVelocity
        );

        telemetry.addData(
                "Shooter Target X",
                aimController.getShooterTargetX()
        );

        telemetry.addData(
                "Shooter Target Y",
                aimController.getShooterTargetY()
        );
    }

    private static double clamp(
            double value,
            double min,
            double max
    ) {
        return Math.max(
                min,
                Math.min(max, value)
        );
    }
}